#!/bin/sh

ln -s pspsh pspthlist
ln -s pspsh psptl
ln -s pspsh pspthsllist
ln -s pspsh pspthdelist
ln -s pspsh pspthsulist
ln -s pspsh pspthdolist
ln -s pspsh pspthinfo
ln -s pspsh pspti
ln -s pspsh pspthsusp
ln -s pspsh pspts
ln -s pspsh pspthspuser
ln -s pspsh pspthresm
ln -s pspsh psptr
ln -s pspsh pspthwake
ln -s pspsh psptw
ln -s pspsh pspthterm
ln -s pspsh psptt
ln -s pspsh pspthdel
ln -s pspsh psptd
ln -s pspsh pspthtdel
ln -s pspsh psptx
ln -s pspsh pspthctx
ln -s pspsh pspthpri
ln -s pspsh psptp
ln -s pspsh pspevlist
ln -s pspsh pspel
ln -s pspsh pspevinfo
ln -s pspsh pspei
ln -s pspsh pspsmlist
ln -s pspsh pspsl
ln -s pspsh pspsminfo
ln -s pspsh pspsi
ln -s pspsh pspmxlist
ln -s pspsh pspxl
ln -s pspsh pspmxinfo
ln -s pspsh pspxi
ln -s pspsh pspcblist
ln -s pspsh pspcl
ln -s pspsh pspcbinfo
ln -s pspsh pspci
ln -s pspsh pspvtlist
ln -s pspsh pspzl
ln -s pspsh pspvtinfo
ln -s pspsh pspzi
ln -s pspsh pspvpllist
ln -s pspsh pspvl
ln -s pspsh pspvplinfo
ln -s pspsh pspvi
ln -s pspsh pspfpllist
ln -s pspsh pspfl
ln -s pspsh pspfplinfo
ln -s pspsh pspfi
ln -s pspsh pspmpplist
ln -s pspsh psppl
ln -s pspsh pspmppinfo
ln -s pspsh psppi
ln -s pspsh pspthevlist
ln -s pspsh psptel
ln -s pspsh pspthevinfo
ln -s pspsh psptei
ln -s pspsh pspthmon
ln -s pspsh psptm
ln -s pspsh pspthmonoff
ln -s pspsh pspsysstat
ln -s pspsh pspmodlist
ln -s pspsh pspml
ln -s pspsh pspmodinfo
ln -s pspsh pspmi
ln -s pspsh pspmodstop
ln -s pspsh pspms
ln -s pspsh pspmodunld
ln -s pspsh pspmu
ln -s pspsh pspmodstun
ln -s pspsh pspmn
ln -s pspsh pspmodload
ln -s pspsh pspmd
ln -s pspsh pspmodstart
ln -s pspsh pspmt
ln -s pspsh pspmodexec
ln -s pspsh pspme
ln -s pspsh pspmodaddr
ln -s pspsh pspma
ln -s pspsh pspldstart
ln -s pspsh pspld
ln -s pspsh pspkill
ln -s pspsh pspdebug
ln -s pspsh pspd
ln -s pspsh pspmodexp
ln -s pspsh pspmp
ln -s pspsh pspmodimp
ln -s pspsh pspmodfindx
ln -s pspsh pspmfx
ln -s pspsh pspapihook
ln -s pspsh pspapihooks
ln -s pspsh pspapihp
ln -s pspsh pspapihd
ln -s pspsh pspmeminfo
ln -s pspsh pspmf
ln -s pspsh pspmemreg
ln -s pspsh pspmr
ln -s pspsh pspmemdump
ln -s pspsh pspdm
ln -s pspsh pspmemblocks
ln -s pspsh pspmk
ln -s pspsh pspsavemem
ln -s pspsh pspsm
ln -s pspsh psploadmem
ln -s pspsh psplm
ln -s pspsh psppokew
ln -s pspsh psppw
ln -s pspsh psppokeh
ln -s pspsh pspph
ln -s pspsh psppokeb
ln -s pspsh psppb
ln -s pspsh psppeekw
ln -s pspsh pspkw
ln -s pspsh psppeekh
ln -s pspsh pspkh
ln -s pspsh psppeekb
ln -s pspsh pspkb
ln -s pspsh pspfillw
ln -s pspsh pspfw
ln -s pspsh pspfillh
ln -s pspsh pspfh
ln -s pspsh pspfillb
ln -s pspsh pspfb
ln -s pspsh pspcopymem
ln -s pspsh pspcm
ln -s pspsh pspfindstr
ln -s pspsh pspns
ln -s pspsh pspfindhex
ln -s pspsh pspnx
ln -s pspsh pspfindw
ln -s pspsh pspnw
ln -s pspsh pspfindh
ln -s pspsh pspnh
ln -s pspsh pspdcache
ln -s pspsh pspdc
ln -s pspsh pspicache
ln -s pspsh pspic
ln -s pspsh pspdisasm
ln -s pspsh pspdi
ln -s pspsh pspdisopts
ln -s pspsh pspdisset
ln -s pspsh pspdisclear
ln -s pspsh pspmemprot
ln -s pspsh pspls
ln -s pspsh pspdir
ln -s pspsh pspchdir
ln -s pspsh pspcd
ln -s pspsh pspcp
ln -s pspsh pspcopy
ln -s pspsh pspmkdir
ln -s pspsh psprm
ln -s pspsh pspdel
ln -s pspsh psprmdir
ln -s pspsh psprd
ln -s pspsh psprename
ln -s pspsh pspren
ln -s pspsh pspremap
ln -s pspsh psppwd
ln -s pspsh pspexprint
ln -s pspsh pspep
ln -s pspsh pspexlist
ln -s pspsh pspexl
ln -s pspsh pspexctx
ln -s pspsh pspec
ln -s pspsh pspexresume
ln -s pspsh pspc
ln -s pspsh pspexprfpu
ln -s pspsh pspef
ln -s pspsh pspexprvfpu
ln -s pspsh pspev
ln -s pspsh pspsetreg
ln -s pspsh pspstr
ln -s pspsh psphwena
ln -s pspsh psphwregs
ln -s pspsh psphwbp
ln -s pspsh pspbpset
ln -s pspsh pspbp
ln -s pspsh pspbpprint
ln -s pspsh pspbt
ln -s pspsh pspstep
ln -s pspsh psps
ln -s pspsh pspskip
ln -s pspsh pspk
ln -s pspsh pspsymload
ln -s pspsh pspsyl
ln -s pspsh pspsymlist
ln -s pspsh pspsyt
ln -s pspsh pspsymprint
ln -s pspsh pspsyp
ln -s pspsh pspsymbyaddr
ln -s pspsh pspsya
ln -s pspsh pspsymbyname
ln -s pspsh pspsyn
ln -s pspsh pspusbstat
ln -s pspsh pspus
ln -s pspsh pspuidlist
ln -s pspsh pspul
ln -s pspsh pspuidinfo
ln -s pspsh pspui
ln -s pspsh pspcop0
ln -s pspsh pspc0
ln -s pspsh pspexit
ln -s pspsh pspquit
ln -s pspsh pspscrshot
ln -s pspsh pspss
ln -s pspsh pspcalc
ln -s pspsh pspreset
ln -s pspsh pspr
ln -s pspsh pspver
ln -s pspsh pspv
ln -s pspsh psppspver
ln -s pspsh pspconfig
ln -s pspsh pspconfset
ln -s pspsh pspconfdel
ln -s pspsh psppower
ln -s pspsh psppoweroff
ln -s pspsh pspclock
ln -s pspsh psptty
ln -s pspsh psptonid
ln -s pspsh pspprofmode
ln -s pspsh pspdebugreg
ln -s pspsh pspenv
ln -s pspsh pspset
ln -s pspsh pspunset
ln -s pspsh pspecho
ln -s pspsh psperror
ln -s pspsh psphelp
